# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.leaseagreement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.invoicebankdetail'),
        ),
    ]
