"""
DEPRECIATION APP — Serializers

Converts DepreciationPolicy and DepreciationSchedule models to/from JSON.

We provide:
  - PolicyListSerializer: lightweight (used in list views)
  - PolicyDetailSerializer: full details with nested schedule rows
  - ScheduleSerializer: for individual schedule rows
"""

from rest_framework import serializers
from assets.serializers import CommaDecimalField
from .models import DepreciationPolicy, DepreciationSchedule


# DEPRECIATION SCHEDULE SERIALIZER
class DepreciationScheduleSerializer(serializers.ModelSerializer):
    """Serializes a single schedule row (one period of depreciation)."""

    class Meta:
        model = DepreciationSchedule
        fields = [
            'id', 'policy', 'period_year',
            'opening_nbv', 'depreciation_amount',
            'accumulated_depreciation', 'closing_nbv',
            'units_used', 'notes',
            'created_at', 'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']


# DEPRECIATION POLICY LIST SERIALIZER (lightweight — for listings)
class DepreciationPolicyListSerializer(serializers.ModelSerializer):
    """
    Lightweight serializer for listing many policies.
    Excludes nested schedule rows to keep list responses fast.
    """

    # Money field accepts comma-separated input like "500,000.00"
    residual_value = CommaDecimalField(max_digits=15, decimal_places=2, required=False)

    # Friendly display values (e.g. "Straight-Line Method" instead of "SLM")
    method_display = serializers.CharField(source='get_method_display', read_only=True)
    standard_display = serializers.CharField(source='get_standard_display', read_only=True)
    status_display = serializers.CharField(source='get_status_display', read_only=True)

    # Show the asset's code and name so the frontend doesn't need a second lookup
    asset_code = serializers.CharField(source='asset.asset_code', read_only=True)
    asset_name = serializers.CharField(source='asset.name', read_only=True)
    acquisition_cost = serializers.DecimalField(
        source='asset.acquisition_cost', max_digits=15, decimal_places=2, read_only=True
    )

    # Who created this policy
    created_by_name = serializers.CharField(
        source='created_by.full_name', read_only=True, default=''
    )

    class Meta:
        model = DepreciationPolicy
        fields = [
            'id', 'asset', 'asset_code', 'asset_name', 'acquisition_cost',
            'method', 'method_display',
            'useful_life_years', 'residual_value',
            'depreciation_rate', 'total_units',
            'standard', 'standard_display',
            'start_date', 'status', 'status_display', 'notes',
            'created_by', 'created_by_name',
            'created_at', 'updated_at',
        ]
        read_only_fields = ['id', 'created_by', 'created_at', 'updated_at']


# DEPRECIATION POLICY DETAIL SERIALIZER (with nested schedules)
class DepreciationPolicyDetailSerializer(DepreciationPolicyListSerializer):
    """
    Full policy details including the complete year-by-year schedule.
    Used for the policy detail page.
    """

    # Nested list of schedule rows for this policy (read-only — generated by engine)
    schedules = DepreciationScheduleSerializer(many=True, read_only=True)

    # Computed field — how many periods are already in the schedule
    schedule_count = serializers.SerializerMethodField()

    # Computed field — total depreciation taken to date (sum across all rows)
    total_depreciation_to_date = serializers.SerializerMethodField()

    # Computed field — most recent NBV (from latest schedule row)
    current_nbv = serializers.SerializerMethodField()

    class Meta(DepreciationPolicyListSerializer.Meta):
        fields = DepreciationPolicyListSerializer.Meta.fields + [
            'schedules', 'schedule_count',
            'total_depreciation_to_date', 'current_nbv',
        ]

    def get_schedule_count(self, obj):
        return obj.schedules.count()

    def get_total_depreciation_to_date(self, obj):
        """Sum the depreciation_amount column across every schedule row."""
        latest = obj.get_latest_schedule()
        return latest.accumulated_depreciation if latest else 0

    def get_current_nbv(self, obj):
        """Closing NBV from the most recent schedule row, or the asset's original cost if none."""
        latest = obj.get_latest_schedule()
        return latest.closing_nbv if latest else obj.asset.acquisition_cost
