# Generated by Django 6.0.6 on 2026-07-13 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('it_equipment', 'IT Equipment'), ('machinery', 'Machinery'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('useful_life_years', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valuation_method', models.CharField(choices=[('cost', 'Cost Method'), ('market', 'Market Method'), ('replacement', 'Replacement Cost Method')], default='cost', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('transferred', 'Transferred'), ('impaired', 'Impaired')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('upgrade', 'Upgrade / Improvement'), ('transfer', 'Transfer'), ('impairment', 'Impairment'), ('revaluation', 'Revaluation'), ('disposal', 'Disposal')], max_length=20)),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Event',
                'verbose_name_plural': 'Asset Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fair_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('cost', 'Cost Method'), ('market', 'Market Method'), ('replacement', 'Replacement Cost Method')], default='cost', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Valuation',
                'verbose_name_plural': 'Asset Valuations',
                'ordering': ['-valuation_date'],
            },
        ),
    ]
