# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetevent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetevent',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
