# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('property', models.ForeignKey(help_text='The building (asset) this unit belongs to.', limit_choices_to={'category': 'building'}, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='assets.asset')),
            ],
        ),
    ]
