# Generated by Django 6.0.6 on 2026-07-13 15:51

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('valuation', 'Valuation Report'), ('depreciation', 'Depreciation Report'), ('nbv_summary', 'Net Book Value Summary')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_assets', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_nbv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_category', models.CharField(blank=True, max_length=30)),
                ('value_at_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('depreciation_for_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Line Item',
                'verbose_name_plural': 'Report Line Items',
                'ordering': ['report', 'asset_code'],
            },
        ),
    ]
