from datetime import date, timedelta
from io import BytesIO
from decimal import Decimal

from django.http import HttpResponse
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from users.permissions import IsAdminOrLeaseOfficer, IsTenant
from invoices.models import Invoice, InvoiceBankDetail
from notifications.services import notify_lease_created
from .models import LeaseAgreement
from .serializers import LeaseAgreementSerializer


def generate_invoice_number():
    last_invoice = Invoice.objects.order_by('-id').first()
    if not last_invoice:
        return 'INV-000001'
    return f'INV-{last_invoice.id + 1:06d}'


def generate_lease_number():
    last_lease = LeaseAgreement.objects.order_by('-id').first()
    if not last_lease:
        return 'LSA-000001'
    return f'LSA-{last_lease.id + 1:06d}'


def build_lease_contract_html(lease, generated_by=None):
    from decimal import Decimal

    unit = lease.unit_description or (lease.unit.unit_number if lease.unit else 'Whole property')
    rent_amount = Decimal(lease.monthly_rent)
    month_count = calculate_month_count(lease.start_date, lease.end_date)
    total_rent = (rent_amount * Decimal(month_count)).quantize(Decimal('0.01'))
    generated_by_text = generated_by or (lease.lease_manager.get_full_name() if lease.lease_manager else 'Lease Manager')

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Lease {lease.lease_number}</title>
<style>
body {{ font-family: Georgia, serif; max-width: 720px; margin: 40px auto; padding: 24px; color: #1e293b; }}
h1 {{ text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 12px; }}
.section {{ margin: 20px 0; }}
.label {{ font-weight: bold; color: #475569; }}
.signature {{ margin-top: 48px; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 1rem; }}
.sig-line {{ border-top: 1px solid #000; width: 220px; margin-top: 40px; text-align: center; font-size: 12px; }}
.note {{ font-size: 0.95rem; color: #475569; margin-top: 16px; }}
</style></head><body>
<h1>LEASE AGREEMENT</h1>
<p style="text-align:center"><strong>Financial Management System</strong></p>
<div class="section"><span class="label">Contract No:</span> {lease.lease_number}</div>
<div class="section"><span class="label">Tenant:</span> {lease.tenant.full_name}</div>
<div class="section"><span class="label">Email:</span> {lease.tenant.email}</div>
<div class="section"><span class="label">Property:</span> {lease.property.name} ({lease.property.asset_code})</div>
<div class="section"><span class="label">Unit:</span> {unit}</div>
<div class="section"><span class="label">Location:</span> {lease.property.location or 'N/A'}</div>
<div class="section"><span class="label">Lease Period:</span> {lease.start_date} to {lease.end_date}</div>
<div class="section"><span class="label">Monthly Rent:</span> {rent_amount:.2f}</div>
<div class="section"><span class="label">Total Rent ({month_count} months):</span> {total_rent:.2f}</div>
<div class="section"><span class="label">Status:</span> {lease.status.upper()}</div>
<p class="note">This agreement is issued under the Financial Management System lease module. The tenant agrees to pay rent on time and comply with property usage terms.</p>
<div class="signature">
<div><div class="sig-line">{generated_by_text}</div></div>
<div><div class="sig-line">Tenant Signature</div></div>
</div>
<p style="font-size:11px;color:#64748b;margin-top:32px">Generated on {date.today()}</p>
</body></html>"""


def build_lease_contract_pdf(lease, generated_by=None):
    """
    Render the lease contract as a PDF using reportlab.

    We used to use weasyprint here, but it depends on GTK-family native
    libraries that aren't installed on Windows dev boxes. Reportlab is
    pure Python and produces reliable output on every platform.
    """
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    unit = lease.unit_description or (lease.unit.unit_number if lease.unit else 'Whole property')
    rent_amount = Decimal(lease.monthly_rent)
    month_count = calculate_month_count(lease.start_date, lease.end_date)
    total_rent = (rent_amount * Decimal(month_count)).quantize(Decimal('0.01'))
    generated_by_text = generated_by or (
        f'Generated by: {lease.lease_manager.get_full_name() or lease.lease_manager.username}'
        if lease.lease_manager else 'Generated by: Lease Manager'
    )

    property_name = getattr(lease.property, 'name', None) or getattr(lease.property, 'asset_name', '') or ''
    property_code = getattr(lease.property, 'asset_code', '') or ''

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
        title=f'Lease {lease.lease_number}',
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'ContractTitle', parent=styles['Title'],
        alignment=TA_CENTER, textColor=colors.HexColor('#1e293b'),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        'ContractSubtitle', parent=styles['Normal'],
        alignment=TA_CENTER, fontSize=11, textColor=colors.HexColor('#475569'),
        spaceAfter=18,
    )
    note_style = ParagraphStyle(
        'ContractNote', parent=styles['Normal'],
        fontSize=10, textColor=colors.HexColor('#475569'),
        leading=14, spaceBefore=14, spaceAfter=20,
    )
    footer_style = ParagraphStyle(
        'ContractFooter', parent=styles['Normal'],
        fontSize=8, textColor=colors.HexColor('#64748b'),
        alignment=TA_CENTER, spaceBefore=18,
    )

    fields = [
        ('Contract No', lease.lease_number),
        ('Tenant', lease.tenant.full_name),
        ('Email', lease.tenant.email),
        ('Property', f'{property_name} ({property_code})' if property_code else property_name),
        ('Unit', unit),
        ('Location', getattr(lease.property, 'location', '') or 'N/A'),
        ('Lease Period', f'{lease.start_date} to {lease.end_date}'),
        ('Monthly Rent', f'{rent_amount:,.2f}'),
        (f'Total Rent ({month_count} months)', f'{total_rent:,.2f}'),
        ('Status', lease.status.upper()),
    ]

    detail_table = Table(fields, colWidths=[5 * cm, 11 * cm])
    detail_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1e293b')),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))

    signature_row = Table(
        [[generated_by_text, 'Tenant Signature']],
        colWidths=[8 * cm, 8 * cm],
    )
    signature_row.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (-1, 0), 0.75, colors.HexColor('#1e293b')),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
    ]))

    story = [
        Paragraph('LEASE AGREEMENT', title_style),
        Paragraph('<b>Financial Management System</b>', subtitle_style),
        detail_table,
        Paragraph(
            'This agreement is issued under the Financial Management System lease module. '
            'The tenant agrees to pay rent on time and comply with property usage terms.',
            note_style,
        ),
        Spacer(1, 40),
        signature_row,
        Paragraph(f'Generated on {date.today()}', footer_style),
    ]

    doc.build(story)
    return buffer.getvalue()


def calculate_month_count(start_date, end_date):
    if end_date < start_date:
        return 0

    months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)
    if end_date.day > start_date.day:
        return months + 1
    return max(months, 1)


def calculate_total_rent(lease):
    rent_amount = Decimal(str(lease.monthly_rent))
    month_count = calculate_month_count(lease.start_date, lease.end_date)
    return (rent_amount * Decimal(month_count)).quantize(Decimal('0.01'))


def create_or_update_lease_invoice(lease, bank_name='', bank_account_number=''):
    invoice = Invoice.objects.filter(lease=lease).order_by('-created_at').first()
    total_rent = calculate_total_rent(lease)
    if invoice:
        invoice.amount = total_rent
        invoice.issue_date = lease.start_date
        invoice.due_date = lease.end_date
        invoice.bank_name = bank_name
        invoice.bank_account_number = bank_account_number
        invoice.save(update_fields=['amount', 'issue_date', 'due_date', 'bank_name', 'bank_account_number'])
        return invoice

    return Invoice.objects.create(
        lease=lease,
        invoice_number=generate_invoice_number(),
        amount=total_rent,
        issue_date=lease.start_date,
        due_date=lease.end_date,
        bank_name=bank_name,
        bank_account_number=bank_account_number,
    )


class LeaseAgreementViewSet(viewsets.ModelViewSet):
    queryset = LeaseAgreement.objects.select_related('tenant', 'property', 'unit', 'lease_manager').all()
    serializer_class = LeaseAgreementSerializer
    permission_classes = [IsAdminOrLeaseOfficer]

    def perform_create(self, serializer):
        lease = serializer.save(
            lease_number=generate_lease_number(),
            lease_manager=self.request.user,
        )
        if lease.unit:
            lease.unit.is_occupied = True
            lease.unit.save(update_fields=['is_occupied'])
        active_bank = InvoiceBankDetail.objects.filter(is_active=True).first()
        bank_name = self.request.data.get('bank_name', '') or (active_bank.bank_name if active_bank else '')
        bank_account_number = self.request.data.get('bank_account_number', '') or (active_bank.account_number if active_bank else '')
        create_or_update_lease_invoice(
            lease,
            bank_name=bank_name,
            bank_account_number=bank_account_number,
        )
        notify_lease_created(lease)

    def perform_destroy(self, instance):
        unit = instance.unit
        super().perform_destroy(instance)
        if unit:
            unit.is_occupied = False
            unit.save(update_fields=['is_occupied'])

    def perform_update(self, serializer):
        old_unit = self.get_object().unit
        lease = serializer.save()
        new_unit = lease.unit
        if old_unit and old_unit.id != (new_unit.id if new_unit else None):
            old_unit.is_occupied = False
            old_unit.save(update_fields=['is_occupied'])
        if new_unit and not new_unit.is_occupied:
            new_unit.is_occupied = True
            new_unit.save(update_fields=['is_occupied'])

    @action(detail=True, methods=['get'], url_path='download-contract')
    def download_contract(self, request, pk=None):
        lease = self.get_object()
        manager_name = request.user.get_full_name() or request.user.username
        pdf_content = build_lease_contract_pdf(lease, generated_by=f'Generated by: {manager_name}')
        response = HttpResponse(pdf_content, content_type='application/pdf')
        filename = f'lease_{lease.lease_number or lease.id}.pdf'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response


class MyLeaseViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = LeaseAgreementSerializer
    permission_classes = [IsAuthenticated, IsTenant]

    def get_queryset(self):
        return LeaseAgreement.objects.select_related(
            'tenant', 'property', 'unit', 'lease_manager',
        ).filter(tenant__user=self.request.user)

    @action(detail=True, methods=['get'], url_path='download-contract')
    def download_contract(self, request, pk=None):
        lease = self.get_object()
        manager_name = lease.lease_manager.get_full_name() if lease.lease_manager else request.user.get_full_name() or request.user.username
        pdf_content = build_lease_contract_pdf(lease, generated_by=f'Generated by: {manager_name}')
        response = HttpResponse(pdf_content, content_type='application/pdf')
        filename = f'lease_{lease.lease_number or lease.id}.pdf'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response
