# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(limit_choices_to={'category': 'building'}, on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyunit'),
        ),
    ]
