# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.PositiveIntegerField()),
                ('opening_nbv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_nbv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('units_used', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depreciation Schedule',
                'verbose_name_plural': 'Depreciation Schedules',
                'ordering': ['policy', 'period_year'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('SLM', 'Straight-Line Method'), ('DBM', 'Declining Balance Method'), ('UPM', 'Units of Production Method')], default='SLM', max_length=10)),
                ('useful_life_years', models.DecimalField(decimal_places=1, max_digits=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Required for Declining Balance Method (e.g. 20.00 for 20%)', max_digits=5, null=True)),
                ('total_units', models.PositiveIntegerField(blank=True, help_text='Required for Units of Production Method (total expected lifetime output)', null=True)),
                ('standard', models.CharField(choices=[('IFRS', 'IFRS (IAS 16)'), ('IPSAS', 'IPSAS 17')], default='IFRS', max_length=10)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_policies', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Depreciation Policy',
                'verbose_name_plural': 'Depreciation Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
