# Generated by Django 6.0.6 on 2026-07-13 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depreciation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationpolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_policies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='depreciation.depreciationpolicy'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationschedule',
            unique_together={('policy', 'period_year')},
        ),
    ]
